### PR TITLE
Manage sequences in the right way

### PR DESCRIPTION
**Pull request by yodeyer**
For sequences, 
- keep only elements defined in the XSD
- put elements in the right order

### CODE REVIEW

**Comment by Marsup** [comment]
Why not contribute back to the original project ?
It seems very much alive.

**Comment by jdassonvil** [comment]
The first few changes we made to the library was a bit ugly and specific to our projects, that's the reason why this fork exists.
But they we'll be deprecated by this version so we'll definitely consider the MR in the next few days.

**Comment by yodeyer** [comment]
I'm not sure that the original project will, one day, respond to our needs: in the original project, not respecting the WSDL seems to be a feature (you can look at all the "dummy" tests), and this is the opposite of what we want.

**Comment by jdassonvil** [comment]
Reading the tests it looks like there's a strict mode. May be we should update this one ? Or add a stricter one ?

**Comment by yodeyer** [comment]
This feature is not documented at all, but when I look at the code, it's for the parsing of the WSDL file, not building of the request you send.

**Comment by jdassonvil** [comment]
:+1: ok for this change

**Comment by Marsup** [comment]
The best way forward is to discuss that with the maintainer, not assume he doesn't want that.

**Pull request merged**
